# -*- coding: utf-8 -*-
"""Task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvRvagOkjRk3WPDlsnVPVD8-X7Gyl7QM
"""

import matplotlib.pyplot as plt

# 1. User Input & Variable Declaration
# We gather data dynamically from the user rather than hardcoding values
print("--- User Setup ---")
user_name = input("Enter your name: ")
is_active = True  # Boolean variable indicating active session

# We use a try-except block here to handle invalid numeric inputs immediately
try:
    user_budget = float(input("Enter your budget for the project (e.g., 500.00): "))
    item_count = int(input("Enter the number of items you need (e.g., 5): "))
except ValueError:
    print("Invalid input detected. Using default values for safety.")
    user_budget = 500.0
    item_count = 5

# 2. Type Inspection
# displaying what type of data Python has stored for each variable
print("\n--- Data Type Inspection ---")
print(f"Variable 'user_name' is type: {type(user_name)}")
print(f"Variable 'user_budget' is type: {type(user_budget)}")
print(f"Variable 'item_count' is type: {type(item_count)}")
print(f"Variable 'is_active' is type: {type(is_active)}")

# 3. Arithmetic Operations
# Calculating cost per item and estimating a tax buffer
item_cost = 45.50
total_cost = item_cost * item_count
remaining_budget = user_budget - total_cost

print("\n--- Financial Calculation ---")
print(f"Cost per item: ${item_cost}")
print(f"Total cost for {item_count} items: ${total_cost}")
print(f"Remaining Budget: ${remaining_budget}")

# 4. String Concatenation
# Manually combining strings and numbers using str() casting
print("\n--- Summary Report ---")
# Note: explicit casting with str() is required when using the + operator
report = "User " + user_name + " has a remaining balance of " + str(remaining_budget)
print(report)

# 5. Dynamic Typing Demonstration
# Python allows a variable to change its type based on the value assigned
print("\n--- Dynamic Typing Demo ---")
dynamic_var = 100
print(f"Value: {dynamic_var} | Type: {type(dynamic_var)}")

dynamic_var = "One Hundred"
print(f"New Value: {dynamic_var} | New Type: {type(dynamic_var)}")

# 6. Visualization (Bonus)
# Visualizing the Budget vs Expenses using Matplotlib
print("\n--- Generating Visualization... ---")

# Data for the chart
categories = ['Total Budget', 'Total Cost', 'Remaining']
values = [user_budget, total_cost, remaining_budget]
colors = ['green', 'red', 'blue']

# Create a bar chart
plt.figure(figsize=(8, 5))
plt.bar(categories, values, color=colors)
plt.title(f"Budget Breakdown for {user_name}")
plt.ylabel("Amount ($)")
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Display the plot
plt.show()